version: 2

sources:
  - name: adventure_works
    schema: adventure_works
    description: The data source is a datawarehouse that is a copy of a postgres database from the company Adventure Works
    tables:
      - name: salesorderdetail
        description: Individual products associated with a specific sales order. See SalesOrderHeader.
      - name: salesorderheader
        description: General sales order information.
      - name: creditcard
        description: Customer credit card information.
      - name: stateprovince
        description: State and province lookup table.
      - name: address  
        description: Street address information for customers, employees, and vendors.
      - name: countryregion
        description: Lookup table containing the ISO standard codes for countries and regions.
      - name: product
        description: Products sold or used in the manfacturing of sold products.
      - name: person
        description: 'Human beings involved with AdventureWorks: employees, customer contacts, and vendor contacts.'
      - name: customer
        description: Current customer information. Also see the Person and Store tables.
      - name: salesreason
        description: Lookup table of customer purchase reasons.
      - name: salesorderheadersalesreason
        description: Cross-reference table mapping sales orders to sales reason codes.